### ISSUE TITLE
grunt jasmine --- TypeError: Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by keltik85** [jsoverson/grunt-jasmine-runner-example#3]
I get this error:

```
$ grunt jasmine
Loading "jasmine.js" tasks...ERROR
>> TypeError: Cannot read property '_' of undefined
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property '_' of undefined
Warning: Cannot read property 'namespace' of undefined Use --force to continue.

Aborted due to warnings.
Fatal error: Cannot read property 'exit' of undefined
C:\Users\altugtekin\IdeaProjects\syse\src\main\webapp\node_modules\grunt\lib\grunt\fail.js:48
  grunt.util.exit(typeof errcode === 'number' ? errcode : fail.code.FATAL_ERROR);
            ^

TypeError: Cannot read property 'exit' of undefined
  at Object.fail.fatal (C:\Users\myUser\IdeaProjects\myProject\src\main\webapp\node_modules\grunt\lib\grunt\fail.js:48:13)
  at process.uncaughtHandler (C:\Users\myUser\IdeaProjects\myProject\src\main\webapp\node_modules\grunt\lib\grunt.js:121:10)
  at emitOne (events.js:77:13)
  at process.emit (events.js:169:7)
  at process._fatalException (node.js:224:26)
```

My Grunt version is this:

```
$ npm grunt --version
2.15.1
$ npm grunt-cli --version
2.15.1
```

What am I doing wrong?

**Comment by TrentonAdams** [comment]
That's actually your npm version, not grunt.  But, I'm having the same problem...
$ grunt --version
grunt-cli v1.2.0
grunt v1.0.1

I couldn't paste a patch in a reasonable way, so I converted the patch to a pdf...

[project.patch.pdf](https://github.com/jsoverson/grunt-jasmine-runner-example/files/965920/project.patch.pdf)
